name: wakelock_plus_macos
description: >-2
  macOS platform implementation of the wakelock_platform_interface for the wakelock plugin.
version: 1.0.0
repository: https://github.com/creativecreatorormaybenot/wakelock/tree/main/wakelock_macos

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=2.11.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  wakelock_plus_platform_interface:
    # TODO: Publish this first to pub.dev, then point to live version.
    path: "../wakelock_plus_platform_interface"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: WakelockPlusMacosPlugin
        fileName: wakelock_plus_macos.dart
